run-name: Deploy project website for version ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"
      - "!v*-*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: poetry
      - run: poetry install --only site
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email \
            "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: Extract major and minor version
        id: version
        run: |
          echo "version=$( echo ${{ github.ref_name }} \
            | sed -E 's/^v([0-9]+)\.([0-9]+)\..*$/\1.\2/' )" >> $GITHUB_OUTPUT
      - run: poetry run mike set-default --allow-undefined latest
      - run: |
          poetry run mike deploy --update-aliases --push --allow-empty \
            ${{ steps.version.outputs.version }} latest
